"""Functions to create a quantum circuit dataset."""
# UNDERSTOOD DETAILS HERE, left out some details in functions where it is clear what they do
# ToDo: Find out if this creates dataset for training or evaluation? -> definitely for training, maybe also evaluation. 


# AUTOGENERATED! DO NOT EDIT! File to edit: ../../src/platform/circuits_generation.ipynb.

# %% auto #0
#from doc: The __all__ variable is a list of strings where each string represents the name of a variable, function, class, or module that you want to expose to wildcard imports.
# allows to import all the listed things using from xy import *
__all__ = ['CircuitConditionType', 'get_rnd_encoded_circuit', 'get_rnd_encoded_circuits', 'generate_circuit_dataset']

# %% ../../src/platform/circuits_generation.ipynb #c82c4d7b-e275-416e-b88d-3d527a9e3bff
from ..imports import *
from .backends.base_backend import BaseBackend
from .tokenizer.circuits_tokenizer import CircuitTokenizer, Vocabulary
from ..dataset.dataset_helper import get_unique_elements_indices
from ..utils.async_fn import MemoryMappedArray, Parallel, delayed

# %% ../../src/platform/circuits_generation.ipynb #297cefeb-ff48-4fdb-9df6-f02b43c518cb
#from doc: enum.Enum is a way to define a set of named constant values, e.g. SRV = 1, UNITARY = 2, used to specify the type of condition for circuit generation. 
class CircuitConditionType(enum.Enum):   
    SRV      = enum.auto() 
    UNITARY  = enum.auto() 

# %% ../../src/platform/circuits_generation.ipynb #c3c07f63-1d6e-4c6f-8079-f78eadccb172
# generate one random circuit
def get_rnd_encoded_circuit(backend: BaseBackend, 
                            tokenizer: CircuitTokenizer,
                            condition: CircuitConditionType,
                            num_of_qubits: int, 
                            gate_pool: Optional[Sequence[str]], # could be None to use full tokenizer vocabulary (default)
                            min_gates: int, 
                            max_gates: int,  
                            rng: np.random.Generator, 
                            optimized: bool = True, # if True optimizes the circuit using the backend's optimization function
                            post_randomize_params: bool = True, # randomize gate parameters after optimization to increase diversity, if False returns the optimized parameters (which may be less diverse)
                            return_params: bool = True) -> Tuple[Any, torch.Tensor, ...]:   # type hint for return: qc (can be anything), condition, qc_tensor, params_tensor (optional)
    """Generate a random circuit with corresponding condition."""

    # default(a,b) returns a if a is not None, else b
    gate_pool = default(gate_pool, tokenizer.vocabulary) # if no gate pool provided, use the full tokenizer vocabulary

    qc = backend.rnd_circuit(num_of_qubits, rng.integers(min_gates, max_gates+1), gate_pool, rng)  # create random circuit
    
    if optimized:          
        qc = backend.optimize_circuit(qc, gate_pool)   
        
    if post_randomize_params: 
        qc = backend.randomize_params(qc, rng)   
    
    match condition:
        case CircuitConditionType.SRV:     # Case 1
            condition = torch.tensor(backend.schmidt_rank_vector(qc))
            
        case CircuitConditionType.UNITARY: # Case 2
            U         = backend.get_unitary(qc)   
            U_r, U_i  = torch.from_numpy(np.real(U)), torch.from_numpy(np.imag(U)) # decompose complex unitary into real & imaginary parts 
            condition = torch.stack([U_r, U_i], dim=0) # and stack them into a 2-channel tensor for conditioning
    
        case _: raise NotImplementedError(f"Not implemented given condition: {condition}")
    
    instructions = backend.backend_to_genqc(qc) # convert to genQC instruction format (list of dicts with gate name, target qubits, and parameters)
    enc_tuple    = tokenizer.encode(instructions, max_gates, return_params_tensor=return_params)  # qc_tensor, params_tensor

    return qc, condition, *enc_tuple

# %% ../../src/platform/circuits_generation.ipynb #d8271eeb-3c07-4a94-8cc1-3a44b9cb37d3
# generate multiple random circuits in a loop, with option to filter unique circuits and to return parameters as tensors.
def get_rnd_encoded_circuits(backend: BaseBackend, 
                             tokenizer: CircuitTokenizer,
                             condition: CircuitConditionType,                                  
                             samples: int, 
                             num_of_qubits: int, 
                             min_gates: int, 
                             max_gates: int,                       
                             min_sub_gate_pool_cnt: int = 1,
                             max_sub_gate_pool_cnt: Optional[int] = None,
                             fixed_sub_gate_pool: Optional[Sequence[str]] = None, # if not provided, will randomly sample a subset of the tokenizer vocabulary for each circuit
                             max_num_params: Optional[int] = None,
                             filter_unique: bool = True,
                             optimized: bool = True,                                                         
                             post_randomize_params: bool = True,
                             return_params: bool = True,
                             silent: bool = False) -> Tuple[torch.Tensor, ...]:
    """
    Generate ´samples´ number of random circuits with corresponding condition. 
    Creates prompts for conditioning.
    """

    if condition not in [CircuitConditionType.SRV, CircuitConditionType.UNITARY]:
        raise NotImplementedError(f"Not implemented {condition}")
    
    sub_gate_pool = fixed_sub_gate_pool
    gate_pool     = list(tokenizer.vocabulary) # list functionality from doc: convert the tokenizer vocabulary (which may be a set or other collection) into a list to allow indexing and random sampling of subsets.

    rng     = np.random.default_rng() 
    n       = len(gate_pool) + 1
    c_range = np.arange(n-1) # range of indices for the gate pool, used for random sampling of subsets. n-1 because we want to sample from the gate pool, which has n-1 gates (since n includes the +1 for the range to be exclusive).

    if exists(max_sub_gate_pool_cnt):
        max_sub_gate_pool_cnt = max(min_sub_gate_pool_cnt, min(max_sub_gate_pool_cnt+1, n))
    else:                             
        max_sub_gate_pool_cnt = n

    #------------------
    # Generate single circuits sequentially
    
    x = []
    y = []    
    
    if condition is CircuitConditionType.UNITARY: 
        u = []
    
    if return_params: 
        p = []   # Note: params is of different size -> keep list

    for i in tqdm(range(samples), disable=silent): # tqdm is a progress bar library, used here to show progress of circuit generation loop. 

        if not exists(fixed_sub_gate_pool):    
            sub_gate_pool_cnt = rng.integers(min_sub_gate_pool_cnt, max_sub_gate_pool_cnt)        
            sub_gate_pool_ind = rng.choice(c_range, size=sub_gate_pool_cnt, replace=False)   

            #NOTE: with this we have always the same ordering of the prompt gates!!
            sub_gate_pool_ind = np.sort(sub_gate_pool_ind)  
            
            sub_gate_pool     = [gate_pool[ind] for ind in sub_gate_pool_ind]

        val = get_rnd_encoded_circuit(backend=backend,
                                      tokenizer=tokenizer,
                                      condition=condition,
                                      num_of_qubits=num_of_qubits,
                                      gate_pool=sub_gate_pool, 
                                      min_gates=min_gates, 
                                      max_gates=max_gates,
                                      rng=rng,
                                      optimized=optimized,
                                      post_randomize_params=post_randomize_params,
                                      return_params=return_params)
        
        if return_params:
            _, cond, qc_tensor, params_tensor = val    
            p.append(params_tensor)
        else:
            _, cond, qc_tensor = val

        x.append(qc_tensor)
        
        match condition:
            case CircuitConditionType.SRV:      
                label = f"Generate SRV: {cond.tolist()}"     
                
            case CircuitConditionType.UNITARY:  
                label = f"Compile using: {[str(gate) for gate in sub_gate_pool]}"           
                u.append(cond)
                
            case _: raise NotImplementedError(f"Not implemented given condition: {condition}")
      
        y.append(label)
        
    #------------------
    # Make tensors unique and combine tensors and arrays

    x = torch.stack(x, dim=0)
    y = np.array(y)

    if condition is CircuitConditionType.UNITARY: 
        u = torch.stack(u, dim=0) 
    
    if filter_unique:
        tensor_unique, tensor_indices = get_unique_elements_indices(x)
        
        x = x[tensor_indices]
        y = y[tensor_indices]         
        if return_params:                             p = [p[i] for i in tensor_indices.tolist()]    
        if condition is CircuitConditionType.UNITARY: u = u[tensor_indices]

        if not silent: 
            print(f"[INFO]: Generated unique circuits: {tensor_unique.shape[0]}.")
    
    if not exists(max_num_params):
        p_max_para  = max(pi.shape[0] for pi in p)
        p_min_value = min(pi.min() if pi.numel()>0 else 0 for pi in p)
        p_max_value = max(pi.max() if pi.numel()>0 else 0 for pi in p)
        if not silent: print(f"[INFO]: No max_num_params provided, infered {p_max_para=}, {p_min_value=} and {p_max_value=}.")
    else:
        if not silent: print(f"[INFO]: Using provided {max_num_params=}.")
        p_max_para = max_num_params
        
    p_t = torch.zeros((len(p), p_max_para, max_gates))
    for i,pi in enumerate(p):
        p_t[i, :pi.shape[0], :pi.shape[1]] = pi
    p = p_t

    # returns tensors for the encoded circuits (x), their corresponding labels (y), unitaries (u, if condition is UNITARY), and parameters (p, if return_params is True). 
    # The function supports filtering unique circuits and can handle large datasets with memory mapping and parallelization.
    if return_params: 
        return x, y, u, p
    return x, y, u 

# %% ../../src/platform/circuits_generation.ipynb #9abc01cb-136e-4d87-bb91-beae08e0bb33
# large scale version intended for bigger compilation datasets, with memory mapping and parallelization. 
# Returns tensors for the encoded circuits (x), their corresponding labels (y), unitaries (u, if condition is UNITARY), 
# and parameters (p, if return_params is True).
def generate_circuit_dataset(backend: BaseBackend, 
                             tokenizer: CircuitTokenizer,
                             condition: CircuitConditionType,                                  
                             total_samples: int,    
                             num_of_qubits: int, 
                             min_gates: int, 
                             max_gates: int,  
                             batch_samples: int = 128,  
                             n_jobs: int = 1,
                             unitary_dtype: torch.dtype = torch.float16,
                             min_sub_gate_pool_cnt: int = 1,
                             max_sub_gate_pool_cnt: Optional[int] = None,
                             fixed_sub_gate_pool: Optional[Sequence[str]] = None,
                             max_num_params: Optional[int] = None,
                             filter_unique: bool = True,
                             optimized: bool = True,                                                         
                             post_randomize_params: bool = True,
                             return_params: bool = True) -> Tuple[torch.Tensor, ...]:
    """
    Generates ´samples´ number of random circuits with corresponding condition. 
    Supports large scale dataset with large unitaries. Uses memory mapping and parallelization.

    - ´unitary_dtype´ only relevant for ´condition=CircuitConditionType.UNITARY´   
    """

    if condition not in [CircuitConditionType.UNITARY]:
        raise NotImplementedError(f"Not implemented {condition=}")

    if not return_params:
        raise NotImplementedError(f"Not implemented {return_params=}")

    total_samples = int(total_samples)
    batch_samples = min(int(batch_samples), total_samples)
    njobs         = max(min(n_jobs, total_samples//batch_samples), 1)

    #------------------
    # Check data sizes

    gen_data = functools.partial(get_rnd_encoded_circuits, 
                                 backend=backend, 
                                 tokenizer=tokenizer,
                                 condition=condition,
                                 samples=batch_samples,        
                                 num_of_qubits=num_of_qubits, 
                                 min_gates=min_gates, 
                                 max_gates=max_gates,
                                 min_sub_gate_pool_cnt=min_sub_gate_pool_cnt,
                                 max_sub_gate_pool_cnt=max_sub_gate_pool_cnt,
                                 fixed_sub_gate_pool=fixed_sub_gate_pool,
                                 max_num_params=max_num_params,
                                 filter_unique=filter_unique,
                                 optimized=optimized,
                                 post_randomize_params=post_randomize_params,
                                 return_params=return_params,
                                 silent=True)
    
    x, y, u, p = gen_data()
    x_global = torch.zeros((total_samples, *x.shape[1:]), dtype=x.dtype) 
    y_global =     np.empty(total_samples, dtype=y.dtype)  
    u_global = torch.zeros((total_samples, 2, u.shape[-2], u.shape[-1]), dtype=unitary_dtype) 
    p_global = torch.zeros((total_samples, *p.shape[1:]), dtype=p.dtype) 

    #------------------
    # Run memory mapped parallel generation

    def _f(idx, x_map, y_map, u_map, p_map):
        x, y, u, p = gen_data()
     
        off  = x.shape[0]
        idx *= batch_samples
    
        x_map[idx:idx+off] = x
        y_map[idx:idx+off] = y
        u_map[idx:idx+off] = u
        p_map[idx:idx+off] = p
    

    def _scope():
        x_map = MemoryMappedArray(x_global)
        y_map = MemoryMappedArray(y_global, type="numpy")
        u_map = MemoryMappedArray(u_global)
        p_map = MemoryMappedArray(p_global)
        
        with Parallel(n_jobs=n_jobs) as parallel:
            loop_set = range(int(np.floor(total_samples/batch_samples)))
            _        = parallel(delayed(_f)(idx, x_map.obj_memmap, y_map.obj_memmap, u_map.obj_memmap, p_map.obj_memmap) for idx in loop_set)

        return x_map.get_obj(), y_map.get_obj(), u_map.get_obj(), p_map.get_obj()
        
    (x_global, x_file), (y_global, y_file), (u_global, u_file), (p_global, p_file) = _scope()
        
    MemoryMappedArray.clean([x_file, y_file, u_file, p_file])

    #------------------
    # Collect results and remove the holes
 
    x_global_nonzero = torch.logical_not((x_global==0).all(-1).all(-1)).nonzero(as_tuple=True)
    print(f"[INFO]: Generated {x_global_nonzero[0].shape[0]} valid circuits.")

    # complex indexing makes copy not view
    x_global = x_global[x_global_nonzero]#.contiguous().clone()
    u_global = u_global[x_global_nonzero]#.contiguous().clone()
    p_global = p_global[x_global_nonzero]#.contiguous().clone()
    y_global = y_global[x_global_nonzero] #np.ascontiguousarray(y_global[x_global_nonzero])

    if filter_unique:
        tensor_unique, tensor_indices = get_unique_elements_indices(x_global)
        
        x_global = x_global[tensor_indices]
        y_global = y_global[tensor_indices]
        u_global = u_global[tensor_indices]
        p_global = p_global[tensor_indices]

        print(f"[INFO]: After filtering unique circuits: {x_global.shape[0]}.")
    
    return x_global, y_global, u_global, p_global
